### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by eddiemonge** [smkamranqadri/atom-angular-material-snippets#2]
Atom 1.8.0 autocomplete doesn't pop up

**Comment by perpetuumstef** [comment]
Ditto to the issue @eddiemonge is having.

**Comment by smkamranqadri** [comment]
resolved and released, please update package.

**Comment by gmanriqueUy** [comment]
The change made [here](https://github.com/smkamranqadri/atom-angular-material-snippets/commit/5ea02b720fc0d75eef8bd648c765d55a630a00be) broke the package for me.

Versions as follow:
- **Atom**: 1.9.4
- **atom-angular-material-snippets**: 1.2.0

Am I missing something?

Thanks!

**Comment by smkamranqadri** [comment]
Make sure you have the latest version of Atom and all packages are updated.

**Comment by gmanriqueUy** [comment]
Atom's version 1.9.4 is the latest, released 19 hours ago.
I tried Atom with only **atom-angular-material-snippets** enabled and it doesn't work either.

I went to the **atom-angular-material-snippets/snippets/atom-angular-material-snippets.cson** and revert the change made [here](https://github.com/smkamranqadri/atom-angular-material-snippets/commit/5ea02b720fc0d75eef8bd648c765d55a630a00be) and after restart Atom, voila: the snippets are working again.

What's the diference between ".source.html" and ".text.html"?
Am I the only one having this problem?

**Comment by smkamranqadri** [comment]
With the new version the syntax is source.html instead of text.html, while it's working on my machine, I will check with others and let you know.

**Comment by eddiemonge** [comment]
still not working for me on 1.9.4

**Comment by smkamranqadri** [comment]
Let me check and get back to you.
